#!/usr/bin/env bash
# ============================================================================
#  Summer TV kiosk — Raspberry Pi (4 / 5, Raspberry Pi OS).
#
#  Turns the Pi into a hallway kiosk: on login it opens Chromium full-screen on
#  the PUBLIC Summer kiosk (https://summer-ttu.fly.dev/kiosk) — no login, read-only.
#  Audio autoplay is on (Summer can speak), the microphone is auto-allowed, and the
#  browser relaunches itself if it ever exits.
#
#  Run once on the Pi:   bash setup.sh
#  Point at a different server:   SUMMER_KIOSK_URL=http://192.168.1.50:8000/kiosk bash setup.sh
# ============================================================================
set -e
URL="${SUMMER_KIOSK_URL:-https://summer-ttu.fly.dev/kiosk}"

# Chromium's package/binary name differs across Pi OS versions.
BROWSER="$(command -v chromium-browser || command -v chromium || true)"
if [ -z "$BROWSER" ]; then
  echo "Chromium not found — installing..."
  sudo apt-get update -y
  sudo apt-get install -y chromium-browser || sudo apt-get install -y chromium
  BROWSER="$(command -v chromium-browser || command -v chromium)"
fi
echo "Using browser: $BROWSER"

LAUNCHER="$HOME/summer-kiosk.sh"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Launch (and keep) Summer full-screen. Generated by pi-kiosk/setup.sh.
URL="$URL"
BROWSER="$BROWSER"

# Best-effort: keep the screen awake on X11 sessions. On Wayland (Pi 5 default),
# disable blanking via: sudo raspi-config -> Display Options -> Screen Blanking -> Off.
xset s off -dpms 2>/dev/null || true
xset s noblank 2>/dev/null || true

# Dedicated profile so a previous unclean shutdown never blocks the kiosk.
PROFILE="\$HOME/.config/summer-kiosk"
mkdir -p "\$PROFILE"

while true; do
  "\$BROWSER" \\
    --kiosk \\
    --noerrdialogs \\
    --disable-infobars \\
    --no-first-run \\
    --autoplay-policy=no-user-gesture-required \\
    --use-fake-ui-for-media-stream \\
    --disable-session-crashed-bubble \\
    --disable-features=Translate \\
    --check-for-update-interval=31536000 \\
    --user-data-dir="\$PROFILE" \\
    "\$URL"
  # If Chromium is closed or crashes, wait a moment and relaunch the kiosk.
  sleep 3
done
EOF
chmod +x "$LAUNCHER"

# Start the kiosk automatically when the desktop session logs in (XDG autostart).
AUTODIR="$HOME/.config/autostart"
mkdir -p "$AUTODIR"
cat > "$AUTODIR/summer-kiosk.desktop" <<EOF
[Desktop Entry]
Type=Application
Name=Summer Kiosk
Comment=Full-screen Summer hallway kiosk
Exec=$LAUNCHER
X-GNOME-Autostart-enabled=true
EOF

echo ""
echo "Summer kiosk installed."
echo "  Launcher : $LAUNCHER"
echo "  Autostart: $AUTODIR/summer-kiosk.desktop"
echo ""
echo "Two recommended one-time settings (sudo raspi-config):"
echo "  - System Options  -> Boot / Auto Login -> Desktop Autologin   (boots straight in)"
echo "  - Display Options -> Screen Blanking    -> Off                 (TV never sleeps)"
echo ""
echo "Start it now without rebooting:  $LAUNCHER &"
